{% set name = "gromacswrapper" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GromacsWrapper-{{ version }}.tar.gz
  sha256: 688b9708dfc5ad118db0a2fb647cae5501d285e212e07a929e8cd2177f7042e3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numkit
    - numpy >=1.0
    - python
    - six

test:
  imports:
    - gromacs
    - gromacs.fileformats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Becksteinlab/GromacsWrapper
  summary: A python wrapper around the Gromacs tools.
  doc_url: https://pythonhosted.org/GromacsWrapper/
  license: GPL-3.0
  license_file: COPYING

extra:
  recipe-maintainers:
    - felix5572
    - AnguseZhang
