---
type_map:
- H
- C
mass_map:
- 1
- 12
init_data_prefix: "/gpfs/share/home/1600017784/yuzhi/methane/init/"
init_data_sys:
- CH4.POSCAR.01x01x01/02.md/sys-0004-0001/deepmd
init_batch_size:
- 8
sys_configs_prefix: "/gpfs/share/home/1600017784/yuzhi/methane/init/"
sys_configs:
- - CH4.POSCAR.01x01x01/01.scale_pert/sys-0004-0001/scale*/00000*/POSCAR
- - CH4.POSCAR.01x01x01/01.scale_pert/sys-0004-0001/scale*/00001*/POSCAR
sys_batch_size:
- 8
- 8
- 8
- 8
_comment: " that's all "
numb_models: 4
default_training_param:
  _comment: that's all
  use_smooth: true
  sel_a:
  - 16
  - 4
  rcut_smth: 0.5
  rcut: 5
  filter_neuron:
  - 10
  - 20
  - 40
  filter_resnet_dt: false
  n_axis_neuron: 12
  n_neuron:
  - 120
  - 120
  - 120
  resnet_dt: true
  coord_norm: true
  type_fitting_net: false
  systems: []
  set_prefix: set
  stop_batch: 2000
  batch_size: 1
  start_lr: 0.001
  decay_steps: 100
  decay_rate: 0.95
  seed: 0
  start_pref_e: 0.02
  limit_pref_e: 2
  start_pref_f: 1000
  limit_pref_f: 1
  start_pref_v: 0
  limit_pref_v: 0
  disp_file: lcurve.out
  disp_freq: 1000
  numb_test: 4
  save_freq: 1000
  save_ckpt: model.ckpt
  disp_training: true
  time_training: true
  profiling: false
  profiling_file: timeline.json
model_devi_dt: 0.002
model_devi_skip: 0
model_devi_f_trust_lo: 0.05
model_devi_f_trust_hi: 0.15
model_devi_e_trust_lo: 10000000000
model_devi_e_trust_hi: 10000000000
model_devi_clean_traj: true
model_devi_jobs:
- sys_idx:
  - 0
  temps:
  - 100
  press:
  - 1
  trj_freq: 10
  nsteps: 300
  ensemble: nvt
  _idx: '00'
- sys_idx:
  - 1
  temps:
  - 100
  press:
  - 1
  trj_freq: 10
  nsteps: 3000
  ensemble: nvt
  _idx: '01'
fp_style: vasp
shuffle_poscar: false
fp_task_max: 20
fp_task_min: 5
fp_pp_path: "/gpfs/share/home/1600017784/yuzhi/methane/"
fp_pp_files:
- POTCAR
fp_incar: "/gpfs/share/home/1600017784/yuzhi/methane/INCAR_methane"
