---
type_map:
- Al
mass_map:
- 27
init_data_prefix: "/gpfs/share/home/1600017784/generator/Al/init/"
init_data_sys:
- al.fcc.02x02x02/02.md/sys-0032/deepmd
- al.hcp.02x02x02/02.md/sys-0016/deepmd
- al.bcc.02x02x02/02.md/sys-0016/deepmd
init_batch_size:
- 1
- 2
- 2
sys_configs:
- - "/gpfs/share/home/1600017784/generator/Al/init/al.fcc.02x02x02/01.scale_pert/sys-0032/scale-1.000/00000[0-4]/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.fcc.02x02x02/01.scale_pert/sys-0032/scale-1.000/00000[5-9]/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.fcc.02x02x02/01.scale_pert/sys-0032/scale-1.000/00001*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.fcc.02x02x02/01.scale_pert/sys-0032/scale-1.000/00002*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.fcc.02x02x02/01.scale_pert/sys-0032/scale-1.000/00003*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.fcc.02x02x02/01.scale_pert/sys-0032/scale-1.000/00004*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.fcc.02x02x02/01.scale_pert/sys-0032/scale-1.000/00005*/POSCAR"
  - "/gpfs/share/home/1600017784/generator/Al/init/al.fcc.02x02x02/01.scale_pert/sys-0032/scale-1.000/00006*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.fcc.02x02x02/01.scale_pert/sys-0032/scale-1.000/00007*/POSCAR"
  - "/gpfs/share/home/1600017784/generator/Al/init/al.fcc.02x02x02/01.scale_pert/sys-0032/scale-1.000/00008*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.hcp.02x02x02/01.scale_pert/sys-0016/scale-1.000/00000[0-4]/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.hcp.02x02x02/01.scale_pert/sys-0016/scale-1.000/00000[5-9]/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.hcp.02x02x02/01.scale_pert/sys-0016/scale-1.000/00001*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.hcp.02x02x02/01.scale_pert/sys-0016/scale-1.000/00002*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.hcp.02x02x02/01.scale_pert/sys-0016/scale-1.000/00003*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.hcp.02x02x02/01.scale_pert/sys-0016/scale-1.000/00004*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.hcp.02x02x02/01.scale_pert/sys-0016/scale-1.000/00005*/POSCAR"
  - "/gpfs/share/home/1600017784/generator/Al/init/al.hcp.02x02x02/01.scale_pert/sys-0016/scale-1.000/00006*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.hcp.02x02x02/01.scale_pert/sys-0016/scale-1.000/00007*/POSCAR"
  - "/gpfs/share/home/1600017784/generator/Al/init/al.hcp.02x02x02/01.scale_pert/sys-0016/scale-1.000/00008*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.bcc.02x02x02/01.scale_pert/sys-0016/scale-1.000/00000[0-4]/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.bcc.02x02x02/01.scale_pert/sys-0016/scale-1.000/00000[5-9]/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.bcc.02x02x02/01.scale_pert/sys-0016/scale-1.000/00001*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.bcc.02x02x02/01.scale_pert/sys-0016/scale-1.000/00002*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.bcc.02x02x02/01.scale_pert/sys-0016/scale-1.000/00003*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.bcc.02x02x02/01.scale_pert/sys-0016/scale-1.000/00004*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.bcc.02x02x02/01.scale_pert/sys-0016/scale-1.000/00005*/POSCAR"
  - "/gpfs/share/home/1600017784/generator/Al/init/al.bcc.02x02x02/01.scale_pert/sys-0016/scale-1.000/00006*/POSCAR"
- - "/gpfs/share/home/1600017784/generator/Al/init/al.bcc.02x02x02/01.scale_pert/sys-0016/scale-1.000/00007*/POSCAR"
  - "/gpfs/share/home/1600017784/generator/Al/init/al.bcc.02x02x02/01.scale_pert/sys-0016/scale-1.000/00008*/POSCAR"
sys_batch_size:
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 1
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
- 2
_comment: " that's all "
numb_models: 4
default_training_param:
  _comment: that's all
  use_smooth: true
  sel_a:
  - 300
  rcut_smth: 2
  rcut: 8
  filter_neuron:
  - 25
  - 50
  - 100
  filter_resnet_dt: false
  n_axis_neuron: 12
  n_neuron:
  - 240
  - 240
  - 240
  resnet_dt: true
  coord_norm: true
  type_fitting_net: false
  systems: []
  set_prefix: set
  stop_batch: 400000
  batch_size: 1
  start_lr: 0.001
  decay_steps: 2000
  decay_rate: 0.95
  seed: 0
  start_pref_e: 0.02
  limit_pref_e: 2
  start_pref_f: 1000
  limit_pref_f: 1
  start_pref_v: 0
  limit_pref_v: 0
  disp_file: lcurve.out
  disp_freq: 2000
  numb_test: 4
  save_freq: 2000
  save_ckpt: model.ckpt
  load_ckpt: model.ckpt
  disp_training: true
  time_training: true
  profiling: false
  profiling_file: timeline.json
model_devi_dt: 0.002
model_devi_skip: 0
model_devi_f_trust_lo: 0.05
model_devi_f_trust_hi: 0.2
model_devi_e_trust_lo: 10000000000
model_devi_e_trust_hi: 10000000000
model_devi_clean_traj: false
model_devi_jobs:
- _idx: 0
  ensemble: npt
  nsteps: 1000
  press:
  - 1
  - 10
  - 100
  - 1000
  - 5000
  - 10000
  - 20000
  - 50000
  sys_idx:
  - 0
  - 8
  - 16
  temps:
  - 50
  - 132
  - 198
  - 264
  trj_freq: 10
- _idx: 1
  ensemble: npt
  nsteps: 1000
  press:
  - 1
  - 10
  - 100
  - 1000
  - 5000
  - 10000
  - 20000
  - 50000
  sys_idx:
  - 1
  - 9
  - 17
  temps:
  - 50
  - 132
  - 198
  - 264
  trj_freq: 10
- _idx: 2
  ensemble: npt
  nsteps: 3000
  press:
  - 1
  - 10
  - 100
  - 1000
  - 5000
  - 10000
  - 20000
  - 50000
  sys_idx:
  - 2
  - 10
  - 18
  temps:
  - 50
  - 132
  - 198
  - 264
  trj_freq: 10
- _idx: 3
  ensemble: npt
  nsteps: 3000
  press:
  - 1
  - 10
  - 100
  - 1000
  - 5000
  - 10000
  - 20000
  - 50000
  sys_idx:
  - 3
  - 11
  - 19
  temps:
  - 50
  - 132
  - 198
  - 264
  trj_freq: 10
- _idx: 4
  ensemble: npt
  nsteps: 3000
  press:
  - 1
  - 10
  - 100
  - 1000
  - 5000
  - 10000
  - 20000
  - 50000
  sys_idx:
  - 4
  - 12
  - 20
  temps:
  - 50
  - 132
  - 198
  - 264
  trj_freq: 10
- _idx: 5
  ensemble: npt
  nsteps: 3000
  press:
  - 1
  - 10
  - 100
  - 1000
  - 5000
  - 10000
  - 20000
  - 50000
  sys_idx:
  - 5
  - 13
  - 21
  temps:
  - 50
  - 132
  - 198
  - 264
  trj_freq: 10
- _idx: 6
  ensemble: npt
  nsteps: 3000
  press:
  - 1
  - 10
  - 100
  - 1000
  - 5000
  - 10000
  - 20000
  - 50000
  sys_idx:
  - 6
  - 14
  - 22
  temps:
  - 50
  - 132
  - 198
  - 264
  trj_freq: 10
- _idx: 7
  ensemble: npt
  nsteps: 3000
  press:
  - 1
  - 10
  - 100
  - 1000
  - 5000
  - 10000
  - 20000
  - 50000
  sys_idx:
  - 7
  - 15
  - 23
  temps:
  - 50
  - 132
  - 198
  - 264
  trj_freq: 10
- _idx: 8
  ensemble: npt
  nsteps: 1000
  press:
  - 1
  - 10
  - 100
  - 1000
  - 5000
  - 10000
  - 20000
  - 50000
  sys_idx:
  - 0
  - 8
  - 16
  temps:
  - 330
  - 396
  - 462
  - 528
  - 594
  trj_freq: 10
fp_style: vasp
shuffle_poscar: false
fp_task_max: 300
fp_task_min: 5
fp_pp_path: "/gpfs/share/home/1600017784/start/data/POTCAR/Al/"
fp_pp_files:
- POTCAR
fp_incar: "/gpfs/share/home/1600017784/start/pku_input_set/INCAR_metal_scf_gpu"
