name: documentation

on:
  push:
    branches:
      - devel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: pip install -r requirements.txt
    - run: sphinx-build -b html doc/ html/
    - uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
