name: Mirror to Gitee Repo

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'deepmodeling'
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          ORGANIZATION: deepmodeling
          SSH_PRIVATE_KEY: ${{ secrets.SYNC_GITEE_PRIVATE_KEY }}
        with:
          source-repo: "https://github.com/deepmodeling/dpgen.git"
          destination-repo: "git@gitee.com:deepmodeling/dpgen.git"
